#!/bin/bash


/usr/bin/echo "Connecting the official repository for Visual Studio Code"

sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'


/usr/bin/echo "Installing Visual Studio Code from the official depository"

sudo dnf install code -y
